### ISSUE TITLE
Work with an SD?

### ISSUE THREAD

**Issue by Fluxanode** [wwatson4506/TeensyEXT4#1]
Will this version work with SD cards for 3.x and 4.x?

**Comment by wwatson4506** [comment]
Sorry for the slow response.
Not with the native SD card port. You would have to use a USB SD card reader. Even then this library is just in the beginning stages of development. It will only mount an EXT4 formatted USB drive and give some stats. I have not had any time to take its development any further. This is still work in progress. I hope to get back to it soon. There is a very big learning curve with EXT4:)

**Comment by wwatson4506** [comment]
A little over a year now I can say yes it does work with SD cards:)
